app/src/Entity/Adresse.php
<?php

namespace App\Entity;

use App\Repository\AdresseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdresseRepository::class)]
class Adresse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 5)]
    private ?string $adress_number = null;

    #[ORM\Column(length: 255)]
    private ?string $street = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 5)]
    private ?string $postal = null;

    #[ORM\Column(length: 50)]
    private ?string $countries = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $adress_complement = null;

    #[ORM\ManyToOne(inversedBy: 'adresses')]
    private ?Users $users = null;

    /**
     * @var Collection<int, Commands>
     */
    #[ORM\OneToMany(targetEntity: Commands::class, mappedBy: 'adresse')]
    private Collection $commands;

    public function __construct()
    {
        $this->commands = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdressNumber(): ?string
    {
        return $this->adress_number;
    }

    public function setAdressNumber(string $adress_number): static
    {
        $this->adress_number = $adress_number;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): static
    {
        $this->street = $street;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getPostal(): ?string
    {
        return $this->postal;
    }

    public function setPostal(string $postal): static
    {
        $this->postal = $postal;

        return $this;
    }

    public function getCountries(): ?string
    {
        return $this->countries;
    }

    public function setCountries(string $countries): static
    {
        $this->countries = $countries;

        return $this;
    }

    public function getAdressComplement(): ?string
    {
        return $this->adress_complement;
    }

    public function setAdressComplement(?string $adress_complement): static
    {
        $this->adress_complement = $adress_complement;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): static
    {
        $this->users = $users;

        return $this;
    }

    /**
     * @return Collection<int, Commands>
     */
    public function getCommands(): Collection
    {
        return $this->commands;
    }

    public function addCommand(Commands $command): static
    {
        if (!$this->commands->contains($command)) {
            $this->commands->add($command);
            $command->setAdresse($this);
        }

        return $this;
    }

    public function removeCommand(Commands $command): static
    {
        if ($this->commands->removeElement($command)) {
            // set the owning side to null (unless already changed)
            if ($command->getAdresse() === $this) {
                $command->setAdresse(null);
            }
        }

        return $this;
    }
}

app/src/Form/AdresseForm.php
<?php

namespace App\Form;

use App\Entity\Adresse;
use App\Entity\Users;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdresseForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('adress_number')
            ->add('street')
            ->add('city')
            ->add('postal')
            ->add('countries')
            ->add('adress_complement')

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Adresse::class,
        ]);
    }
}

app/src/Controller/AdresseController.php
<?php

namespace App\Controller;

use App\Entity\Adresse;
use App\Entity\Commands;
use App\Form\AdresseForm;
use App\Repository\AdresseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/adresse')]
final class AdresseController extends AbstractController
{
    #[Route(name: 'app_adresse_index', methods: ['GET'])]
    public function index(AdresseRepository $adresseRepository): Response
    {
        return $this->render('adresse/index.html.twig', [
            'adresses' => $adresseRepository->findAll(),
        ]);
    }

    #[Route('/ajouter', name: 'app_adresse_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $adresse = new Adresse();

        $form = $this->createForm(AdresseForm::class, $adresse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
             $adresse->setUsers($this->getUser());

            $entityManager->persist($adresse);

            $entityManager->flush();

            return $this->redirectToRoute('app_adresse_index', ['id'=>$adresse->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('adresse/new.html.twig', [
            'adresse' => $adresse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_adresse_show', methods: ['GET'])]
    public function show(Adresse $adresse): Response
    {
        return $this->render('adresse/show.html.twig', [
            'adresse' => $adresse,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_adresse_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Adresse $adresse, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AdresseForm::class, $adresse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_adresse_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('adresse/edit.html.twig', [
            'adresse' => $adresse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_adresse_delete', methods: ['POST'])]
    public function delete(Request $request, Adresse $adresse, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adresse->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($adresse);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_adresse_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/adresse/_delete_form.html.twig
<form method="post" action="{{ path('app_adresse_delete', {'id': adresse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ adresse.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/adresse/_form.html.twig
{{ form_start(form,{ attr: { class: 'formulaire' } }) }}
<div>
  {{ form_widget(form) }}
</div>

    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/templates/adresse/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Adresse{% endblock %}

{% block body %}
    <h1>Edit Adresse</h1>

    {{ include('adresse/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_adresse_index') }}">back to list</a>

    {{ include('adresse/_delete_form.html.twig') }}
{% endblock %}

app/templates/adresse/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adresse index{% endblock %}

{% block body %}
    <h1>Adresse index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Adress_number</th>
                <th>Street</th>
                <th>City</th>
                <th>Postal</th>
                <th>Countries</th>
                <th>Adress_complement</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for adresse in adresses %}
            <tr>
                <td>{{ adresse.id }}</td>
                <td>{{ adresse.adressNumber }}</td>
                <td>{{ adresse.street }}</td>
                <td>{{ adresse.city }}</td>
                <td>{{ adresse.postal }}</td>
                <td>{{ adresse.countries }}</td>
                <td>{{ adresse.adressComplement }}</td>
                <td>
                    <a href="{{ path('app_adresse_show', {'id': adresse.id}) }}">show</a>
                    <a href="{{ path('app_adresse_edit', {'id': adresse.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_adresse_new') }}">Create new</a>
{% endblock %}

app/templates/adresse/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Adresse{% endblock %}

{% block body %}
    <h1>Create new Adresse</h1>

    {{ include('adresse/_form.html.twig') }}

    <a href="{{ path('app_adresse_index') }}">back to list</a>
{% endblock %}

app/templates/adresse/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adresse{% endblock %}

{% block body %}
    <h1>Adresse</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ adresse.id }}</td>
            </tr>
            <tr>
                <th>Adress_number</th>
                <td>{{ adresse.adressNumber }}</td>
            </tr>
            <tr>
                <th>Street</th>
                <td>{{ adresse.street }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ adresse.city }}</td>
            </tr>
            <tr>
                <th>Postal</th>
                <td>{{ adresse.postal }}</td>
            </tr>
            <tr>
                <th>Countries</th>
                <td>{{ adresse.countries }}</td>
            </tr>
            <tr>
                <th>Adress_complement</th>
                <td>{{ adresse.adressComplement }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_adresse_index') }}">back to list</a>

    <a href="{{ path('app_adresse_edit', {'id': adresse.id}) }}">edit</a>

    {{ include('adresse/_delete_form.html.twig') }}
{% endblock %}